// Generated by browser/pack.py; do not edit.
#pragma once
#include <cstdint>
namespace recovery_ui2::web {
constexpr uint64_t kCompressedBytes = 40956556ULL;
constexpr uint64_t kExpandedBytes = 210785213ULL;
constexpr char kCompressedHash[] = "1e32fb8f722785ca35e02d8961cfe70c492f064adbd03c7efbae27c998afde62";
constexpr char kExpandedHash[] = "99409fd40046bb18658126686019665252e12a5e59283f82a53398710c7b9c2e";
constexpr uint32_t kMemberCount = 445;
}
