// Generated by browser/pack.py; do not edit.
#pragma once
#include <cstdint>
namespace recovery_ui2::web {
constexpr uint64_t kCompressedBytes = 40992424ULL;
constexpr uint64_t kExpandedBytes = 210774149ULL;
constexpr char kCompressedHash[] = "37338fc690a6ab2ab536be4af88070181c38ef65e8ad3474fe75b777b5cacb30";
constexpr char kExpandedHash[] = "bf854c5e7d414d0b3eb96c8931ce012c573d426ba8540543fcb3444cc7c2c560";
constexpr uint32_t kMemberCount = 445;
}
