#!/usr/bin/env python3
"""Pack the approved 4x4 Home artwork atlas as lossless gray texture data."""
import argparse
import pathlib
import zlib
from PIL import Image

parser = argparse.ArgumentParser()
parser.add_argument("atlas", type=pathlib.Path)
parser.add_argument("output", type=pathlib.Path)
args = parser.parse_args()
atlas = Image.open(args.atlas).convert("L")
width, height = 360, 270
pixels = bytearray()
for index in range(15):
    col, row = index % 4, index // 4
    tile = atlas.crop((round(col * atlas.width / 4), round(row * atlas.height / 4),
                       round((col + 1) * atlas.width / 4), round((row + 1) * atlas.height / 4)))
    pixels.extend(tile.resize((width, height), getattr(Image, "Resampling", Image).LANCZOS).tobytes())
data = zlib.compress(pixels, 9)
lines = ["// Generated by tools/pack_home_art.py; do not edit pixel data.",
         f"constexpr int kArtWidth = {width}, kArtHeight = {height}, kArtCount = 15;",
         "constexpr unsigned char kHomeArtCompressed[] = {"]
lines += ["  " + ",".join(str(v) for v in data[i:i+24]) + "," for i in range(0, len(data), 24)]
lines.append("};\n")
args.output.write_text("\n".join(lines))
print(f"{len(pixels)} gray bytes -> {len(data)} compressed bytes")
